repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: debug-statements
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black
        args: [--line-length=88, --target-version=py38]
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.254
    hooks:
    -   id: ruff
        args: [--fix]
-   repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.298
    hooks:
    -   id: pyright
        additional_dependencies: [discord.py==2.2.2]
