name: Lint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2.3.4

      - name: Set up Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.8

      - name: Install Python tools
        run: pip install --upgrade pip setuptools wheel pylint black bandit
        
      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Run pylint
        run: |
          pylint bot.py
          pylint cogs
          pylint utils

      - name: Run black
        run: black --verbose --check --diff .

      - name: Run bandit
        run: bandit -r .
